const ActionTypes = {
    GET_ROBOTS_DATA: "GET_ROBOTS_DATA",
    SET_ROBOTS_DATA: "SET_ROBOTS_DATA",
    DO_EXTINGUISH: "DO_EXTINGUISH",
    DO_RECYCLE: "DO_RECYCLE",
    CHECK_EXTINGUISH: "CHECK_EXTINGUISH"
};

export default ActionTypes;
