const ActionTypes = {
    GET_ROBOTS_DATA: "GET_ROBOTS_DATA",
    SET_ROBOTS_DATA: "SET_ROBOTS_DATA",
    DO_EXTINGUISH: "DO_EXTINGUISH",
    DO_RECYCLE: "DO_RECYCLE",
    CHECK_EXTINGUISH: "CHECK_EXTINGUISH",
    ADD_TO_SHIPMENT: "ADD_TO_SHIPMENT",
    REMOVE_FROM_SHIPMENT: "REMOVE_FROM_SHIPMENT",
    SEND_SHIPMENT: "SEND_SHIPMENT"
};

export default ActionTypes;
